services:

  # MySQL Database
  db:
    image: mariadb:11.3
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MiseAuVert
      MYSQL_USER: miseauvert
      MYSQL_PASSWORD: miseauvert
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - infra_net


  # PhpMyAdmin for MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - infra_net
    depends_on:
      - db

networks:
  infra_net:

volumes:
  db_data:
  glpi_data:
