services:
  app:
    image: php:8.2-apache
    container_name: laravel_app
    ports:
      - '8083:80'
    volumes:
      - ./website:/var/www/html
    working_dir: /var/www/html
    networks:
      - infra_net
    depends_on:
      - db
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip git &&
      docker-php-ext-configure gd --with-freetype --with-jpeg &&
      docker-php-ext-install pdo pdo_mysql gd &&
      a2enmod rewrite &&
      apache2-foreground
      "

  # MySQL Database
  db:
    image: mariadb:11.3
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MiseAuVert
      MYSQL_USER: miseauvert
      MYSQL_PASSWORD: miseauvert
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - infra_net

  # GLPI (Web Interface for ITSM)
  glpi:
    image: diouxx/glpi
    container_name: glpi
    restart: always
    ports:
      - "8080:80"
    environment:
      - TIMEZONE=Europe/Paris
    volumes:
      - glpi_data:/var/www/html/glpi
    networks:
      - infra_net
    depends_on:
      - db

  # PhpMyAdmin for MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - infra_net
    depends_on:
      - db

  # OCS Inventory (Inventory + Agents connection)
  ocs:
    image: ocsinventory/ocsinventory-docker-image:latest
    container_name: ocs_server
    restart: always
    environment:
      - OCS_DB_HOST=db
      - OCS_DB_NAME=ocsweb
      - OCS_DB_USER=ocsuser
      - OCS_DB_PASS=ocspassword
    ports:
      - "8082:80"
    networks:
      - infra_net
    depends_on:
      - db

networks:
  infra_net:

volumes:
  db_data:
  glpi_data:
